server:  
   port: ${PORT:9292}
   servlet:
      session:
         timeout: 1800 # Session timeout. If a duration suffix is not specified, seconds is used.                

eureka:
   client:
      enabled: false

#logging:
#  level: INFO
  
security:
   activation:
      status: false      
   # basic auth credentials
   user:
      name: bigpi
      password: password
     
#use for admin client
management:
   security:
      enabled: false
      
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patternSearchdb
    username: postgres
    password: 123
#    readOnly: true
#    editable: true
    
  jpa:
      hibernate.ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
#            format_sql: true
      
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

application:
#   fheServerData: http://10.8.34.73:9090
#   fheServerAnalysis: http://10.8.34.73:9191

#   seal:
#     sealDir: /home/hgnguyen/Desktop/seal
#     dataDir: ${application.seal.sealDir}/data/
#     resultDir: ${application.seal.sealDir}/result/
#     uploadDir: ${application.seal.sealDir}/upload/
#     keyDir: ${application.seal.sealDir}/keys/
#     sample: 40
#     filename: l
#     encryptPath: ${application.seal.sealDir}/patternSearch_encrypt_v2
#     decryptPath: ${application.seal.sealDir}/patternSearch_decrypt_v2
#     decrypCheckedResulttPath: ${application.seal.sealDir}/patternSearch_decrypt_result_v2
#     evaluatePath: ${application.seal.sealDir}/patternSearch_evaluate_v2
   

   fheServerData: http://localhost:9090
   fheServerAnalysis: http://localhost:9191
#   fheServerData: http://10.8.34.73:9090
#   fheServerAnalysis: http://10.8.34.73:9191

   seal:
#    FilesStorageServiceImpl & FHEPatternSearchService
     sealDir: /opt/fhe/datalake/seal
#     sealDir: /opt/fhe/seal/bin/patternSearch
     dataDir: ${application.seal.sealDir}/data/
     resultDir: ${application.seal.sealDir}/result/
     uploadDir: ${application.seal.sealDir}/upload/
     keyDir: ${application.seal.sealDir}/keys/
     sample: 40
     filename: l
     patternSearchBin: /opt/fhe/seal/bin/patternSearch
     encryptPath: ${application.seal.patternSearchBin}/patternSearch_encrypt_v2
     decryptPath: ${application.seal.patternSearchBin}/patternSearch_decrypt_v2
     decrypCheckedResulttPath: ${application.seal.patternSearchBin}/patternSearch_decrypt_result_v2
     evaluatePath: ${application.seal.patternSearchBin}/patternSearch_evaluate_v2
#     keyDir: ${application.seal.patternSearchBin}/keys/
      
      
         